on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # اختبار التفاعل مع GitHub Actions
      - name: 'Testing Actions of The GitHub'
        run: pwd

      # طباعة الاسم
      - name: 'Testing Printing The Name'
        run: echo 'Maram Basyouny'

      # طباعة محتويات المجلد قبل استخدام actions
      - name: 'Printing File Content Before using uses'
        run: ls

      # استخدام action للتحقق من الشيفرة المصدرية
      - name: 'Checkout code'
        uses: actions/checkout@v3

      # طباعة محتويات المجلد بعد استخدام action
      - name: 'Printing File Content After using uses'
        run: ls

      # تسجيل الدخول إلى Docker Hub
      - name: 'Login to Docker Hub'
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          
      # قد تحتاج إلى خطوة إضافية هنا إذا كنت تريد بناء صورة Docker أو أي خطوة أخرى
      # - name: 'Build Docker Image'
      #   run: |
      #     docker build -t your_image_name .
